import { useEffect, useState } from "react";
import { dashboard } from "../../../services/DashboardService";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import Loader from "../../common/Loader";
import {
    Chart as ChartJS,
    CategoryScale,
    LinearScale,
    BarElement,
    ArcElement,
    Tooltip,
    Legend,
    LineElement,
    PointElement,
    RadialLinearScale
} from "chart.js";

import { Bar, Pie, Line, Doughnut } from "react-chartjs-2";

ChartJS.register(
    CategoryScale,
    LinearScale,
    BarElement,
    ArcElement,
    Tooltip,
    Legend,
    LineElement,
    PointElement,
    RadialLinearScale
);

export default function AdminDashboard() {

    // STATE (FIRST)
    const [stats, setStats] = useState({
        total: 0,
        resolved: 0,
        pending: 0,
        inProgress: 0,
        rejected: 0,
        categoryStats: []
    });

    const [latestIssues, setLatestIssues] = useState([]);
    const safeStats = stats || {};
    const categories = stats?.categoryStats || [];
    const issues = latestIssues || [];
    const [showReportsModal, setShowReportsModal] = useState(false);
    const [loading, setLoading] = useState(true);

    //FETCH DASHBOARD -> API CALL
    const fetchDashboard = async () => {
        try {
            const res = await dashboard();

            if (res.data.success) {
                const data = res.data.data;

                setStats({
                    total: data.counts?.total || 0,
                    resolved: data.counts?.resolved || 0,
                    pending: data.counts?.pending || 0,
                    inProgress: data.counts?.inProgress || 0,
                    rejected: data.counts?.rejected || 0,
                    categoryStats: data.categoryStats || []
                });

                setLatestIssues(data.latestIssues || []);
                setLatestIssues(data.latestIssues || []);
            }

        } catch (err) {
            console.log(err);
        }
        finally {
            setLoading(false);
        }
    };
    useEffect(() => {
        fetchDashboard();
    }, []);

    const employeeMap = {};

    issues.forEach((issue) => {
        const empName = issue.assignedTo?.name || "Unassigned";

        employeeMap[empName] = (employeeMap[empName] || 0) + 1;
    });

    const employeeLabels = Object.keys(employeeMap);
    const employeeData = Object.values(employeeMap);

    const downloadReport = () => {
        const doc = new jsPDF();

        // TITLE 
        doc.setFontSize(22);
        doc.setTextColor(40, 40, 40);

        doc.text("Civora Analytics Report", 14, 22);

        // DATE 
        doc.setFontSize(11);

        doc.text(
            `Generated On: ${new Date().toLocaleString()}`,
            14,
            30
        );

        // OVERVIEW 
        doc.setFontSize(16);

        doc.text("Complaint Overview", 14, 45);

        autoTable(doc, {
            startY: 50,

            head: [["Metric", "Value"]],

            body: [
                ["Total Complaints", stats.total],
                ["Resolved", stats.resolved],
                ["Pending", stats.pending],
                ["In Progress", stats.inProgress],
                ["Rejected", stats.rejected]
            ]
        });

        // CATEGORY TABLE 
        doc.text(
            "Category Analytics",
            14,
            doc.lastAutoTable.finalY + 15
        );

        autoTable(doc, {

            startY: doc.lastAutoTable.finalY + 20,

            head: [["Category", "Complaints"]],

            body: categories.map((cat) => [
                cat.name,
                cat.value
            ])
        });

        // EMPLOYEE TABLE 
        doc.text(
            "Employee Performance",
            14,
            doc.lastAutoTable.finalY + 15
        );

        autoTable(doc, {

            startY: doc.lastAutoTable.finalY + 20,

            head: [["Employee", "Assigned Issues"]],

            body: employeeLabels.map((emp, index) => [
                emp,
                employeeData[index]
            ])
        });

        // FOOTER
        doc.setFontSize(10);

        doc.text(
            "Generated by CIVORA Smart Civic Management System",
            14,
            doc.internal.pageSize.height - 10
        );

        // ================= SAVE PDF =================
        doc.save("CIVORA_Report.pdf");
    };

    //COUNTS ISSUE PER DAY & BUILD DATASET
    const dailyMap = {};

    issues.forEach((issue) => {
        const date = new Date(issue.createdAt)
            .toLocaleDateString("en-CA");   //YYYY-MM-DD

        dailyMap[date] = (dailyMap[date] || 0) + 1;
    });



    const getLast7Days = () => {
        const days = [];

        for (let i = 6; i >= 0; i--) {
            const d = new Date();
            d.setDate(d.getDate() - i);

            const key = d.toISOString().split("T")[0];
            days.push(key);
        }

        return days;
    };

    const last7Days = getLast7Days();

    const activityMap = {};

    // initialize all 7 days with 0
    last7Days.forEach(date => {
        activityMap[date] = 0;
    });

    // fill with backend data
    issues.forEach(issue => {
        const key = new Date(issue.createdAt)
            .toISOString()
            .split("T")[0];

        if (activityMap[key] !== undefined) {
            activityMap[key] += 1;
        }
    });

    const dailyLabels = last7Days.map(date =>
        new Date(date).toLocaleDateString("en-IN", {
            day: "numeric",
            month: "short"
        })
    );

    const dailyCounts = last7Days.map(date => activityMap[date]);


    return (
        <>
            <div className="admin-dashboard">
                {/* ================= STATS ================= */}
                <section className="hotel-hero section">
                    <div className="container hero-stats">
                        <div className="row text-center">

                            <StatCard icon="bi-collection" label="Total Complaints" value={stats?.total} />
                            <StatCard icon="bi-check-circle" label="Resolved" value={stats?.resolved} />
                            <StatCard icon="bi-clock" label="Pending" value={stats?.pending} />
                            <StatCard icon="bi-gear" label="In Progress" value={stats?.inProgress} />

                        </div>
                    </div>
                </section>

                {/* ================= MAIN LAYOUT ================= */}
                <section className="location-cards section">
                    <div className="container">
                        <div className="row gy-5">

                            {/* ================= LEFT PANEL ================= */}
                            <div className="col-lg-8">

                                {/* TITLE */}
                                <div className="section-title">
                                    <span className="description-title">Latest Complaints</span>
                                    <h2>Latest Complaints</h2>
                                </div>

                                <div className="row gy-3">
                                    {loading ? (

                                        // ================= SKELETON UI =================
                                        [...Array(4)].map((_, index) => (
                                            <div key={index} className="col-md-6">

                                                <div className="shadow-sm border rounded bg-white overflow-hidden">

                                                    {/* IMAGE SKELETON */}
                                                    <div
                                                        className="skeleton"
                                                        style={{
                                                            height: "160px",
                                                            width: "100%"
                                                        }}
                                                    />

                                                    <div className="p-3">

                                                        {/* TITLE */}
                                                        <div
                                                            className="skeleton mb-2"
                                                            style={{ height: "18px", width: "80%" }}
                                                        />

                                                        {/* DESCRIPTION */}
                                                        <div
                                                            className="skeleton mb-2"
                                                            style={{ height: "14px", width: "100%" }}
                                                        />
                                                        <div
                                                            className="skeleton mb-3"
                                                            style={{ height: "14px", width: "70%" }}
                                                        />

                                                        {/* USER + LOCATION */}
                                                        <div className="d-flex justify-content-between">

                                                            <div
                                                                className="skeleton"
                                                                style={{ height: "12px", width: "40%" }}
                                                            />

                                                            <div
                                                                className="skeleton"
                                                                style={{ height: "12px", width: "40%" }}
                                                            />

                                                        </div>

                                                    </div>
                                                </div>
                                            </div>
                                        ))

                                    ) : (

                                        // ================= REAL DATA =================
                                        latestIssues?.slice(0, 4).map((issue) => (
                                            <div key={issue._id} className="col-md-6">

                                                <div className="area-highlight shadow-sm border rounded bg-white overflow-hidden">

                                                    {/* IMAGE */}
                                                    <div className="area-image-wrapper position-relative">

                                                        <img
                                                            src={`${issue.media[0]}`}
                                                            alt={issue.title}
                                                            className="img-fluid w-100"
                                                            style={{ height: "160px", objectFit: "cover" }}
                                                        />

                                                        <div className="area-badge">
                                                            <span>{issue.status}</span>
                                                        </div>

                                                        <span
                                                            className="badge bg-dark position-absolute"
                                                            style={{ top: "10px", left: "10px" }}
                                                        >
                                                            {issue.categoryId?.name || "Uncategorized"}
                                                        </span>

                                                    </div>

                                                    {/* CONTENT */}
                                                    <div className="area-info p-4 pt-1">

                                                        <div className="d-flex align-items-center justify-content-between gap-2 mb-1">

                                                            {/* TITLE */}
                                                            <h5
                                                                className="mb-0"
                                                                style={{
                                                                    fontSize: "18px",
                                                                    fontWeight: "600"
                                                                }}
                                                            >
                                                                {issue.title}
                                                            </h5>

                                                            {/* AI SEVERITY BADGE */}
                                                            <div
                                                                className="d-flex align-items-center gap-1 px-2 py-1 rounded-pill"
                                                                style={{
                                                                    background:
                                                                        issue.aiSeverityScore >= 8
                                                                            ? "rgba(220,53,69,0.12)"
                                                                            : issue.aiSeverityScore >= 5
                                                                                ? "rgba(245,158,11,0.12)"
                                                                                : "rgba(25,135,84,0.12)",

                                                                    border:
                                                                        issue.aiSeverityScore >= 8
                                                                            ? "1px solid rgba(220,53,69,0.3)"
                                                                            : issue.aiSeverityScore >= 5
                                                                                ? "1px solid rgba(245,158,11,0.3)"
                                                                                : "1px solid rgba(25,135,84,0.3)",

                                                                    minWidth: "fit-content"
                                                                }}
                                                            >

                                                                <span style={{ fontSize: "14px" }}>
                                                                    ⚡
                                                                </span>

                                                                <span
                                                                    className="fw-semibold"
                                                                    style={{
                                                                        fontSize: "12px",

                                                                        color:
                                                                            issue.aiSeverityScore >= 8
                                                                                ? "#dc3545"
                                                                                : issue.aiSeverityScore >= 5
                                                                                    ? "#d97706"
                                                                                    : "#198754"
                                                                    }}
                                                                >
                                                                    {issue.aiSeverityScore}/10
                                                                </span>

                                                            </div>

                                                        </div>

                                                        <p className="text-muted mb-2" style={{ fontSize: "14px" }}>
                                                            {issue.description?.length > 80
                                                                ? issue.description.slice(0, 80) + "..."
                                                                : issue.description}
                                                        </p>

                                                        <div className="d-flex justify-content-between align-items-center mb-2">

                                                            <small className="text-secondary">
                                                                👤 {issue.reportedBy?.name || "User"}
                                                            </small>

                                                        </div>

                                                        <small className="text-secondary ">
                                                            📍 {issue.location || "Not provided"}
                                                        </small>
                                                    </div>

                                                </div>

                                            </div>
                                        ))
                                    )}

                                </div>
                            </div>

                            {/* ================= RIGHT PANEL ================= */}
                            <div className="col-lg-4">
                                <div className="location-overview ">

                                    <div className="overview-header">
                                        <div className="location-marker">
                                            <i className="bi bi-shield-check" />
                                        </div>

                                        <h3>Platform Insights</h3>

                                        <p className="overview-subtitle">
                                            Smart civic monitoring system for efficient complaint handling and public issue management.
                                        </p>
                                    </div>

                                    <div className="benefits-list mb-4">

                                        {/* REAL-TIME TRACKING */}
                                        <div className="benefit-item">
                                            <div className="benefit-icon">
                                                <i className="bi bi-broadcast-pin" />
                                            </div>

                                            <div className="benefit-content">
                                                <h6>Real-Time Issue Tracking</h6>
                                                <span>
                                                    Monitor complaint progress from submission to resolution
                                                </span>
                                            </div>
                                        </div>

                                        {/* MEDIA EVIDENCE */}
                                        <div className="benefit-item">
                                            <div className="benefit-icon">
                                                <i className="bi bi-camera-fill" />
                                            </div>

                                            <div className="benefit-content">
                                                <h6>Media-Based Reporting</h6>
                                                <span>
                                                    Citizens upload photos and videos as issue evidence
                                                </span>
                                            </div>
                                        </div>

                                        {/* LOCATION */}
                                        <div className="benefit-item">
                                            <div className="benefit-icon">
                                                <i className="bi bi-geo-alt-fill" />
                                            </div>

                                            <div className="benefit-content">
                                                <h6>Location Intelligence</h6>
                                                <span>
                                                    Exact issue locations help departments respond faster
                                                </span>
                                            </div>
                                        </div>

                                        {/* ROLE MANAGEMENT */}
                                        <div className="benefit-item">
                                            <div className="benefit-icon">
                                                <i className="bi bi-people-fill" />
                                            </div>

                                            <div className="benefit-content">
                                                <h6>Department Collaboration</h6>
                                                <span>
                                                    Admins and employees coordinate issue resolution efficiently
                                                </span>
                                            </div>
                                        </div>

                                        <div className="benefit-item">
                                            <div className="benefit-icon">
                                                <i className="bi bi-people-fill" />
                                            </div>

                                            <div className="benefit-content">
                                                <h6>Automated Workflows</h6>
                                                <span>
                                                    Smart routing instantly assigns civic issues to the right municipal team
                                                </span>
                                            </div>

                                        </div>
                                    </div>

                                    <button
                                        className="location-guide-btn border-0 w-100 p-3"
                                        onClick={() => setShowReportsModal(true)}
                                    >
                                        <span>View Full Reports</span>
                                        <i className="bi bi-arrow-right" />
                                    </button>

                                </div>
                            </div>

                        </div>
                    </div>
                </section>

                {/* ================= ANALYTICS ================= */}
                <section className="analytics-section container mt-5" >
                    <div className="section-title ">
                        <span className="description-title">Analytics Overview</span>
                        <h2>Analytics Overview</h2>
                    </div>

                    {/* ROW 1 */}
                    <div className="row gy-4">

                        {/* PIE CHART FIXED */}
                        <div className="col-md-6">
                            <h4 className="mb-2">Status Distribution</h4>
                            <div
                                className="card p-3 shadow-sm border-0 d-flex justify-content-center align-items-center"
                                style={{ height: "380px" }}
                            >
                                <div style={{ width: "100%", height: "300px" }}>
                                    <Pie
                                        data={{
                                            labels: ["Resolved", "Pending", "In Progress", "Rejected"],
                                            datasets: [
                                                {
                                                    label: "Status Distribution",
                                                    data: [
                                                        safeStats.resolved,
                                                        safeStats.pending,
                                                        safeStats.inProgress,
                                                        safeStats.rejected
                                                    ],
                                                    backgroundColor: [
                                                        "#28a745",
                                                        "#ffc107",
                                                        "#007bff",
                                                        "#dc3545"
                                                    ]
                                                }
                                            ]
                                        }}
                                        options={{
                                            responsive: true,
                                            maintainAspectRatio: false,
                                            plugins: {
                                                legend: {
                                                    position: "right"   // ✅ vertical legend fix
                                                }
                                            }
                                        }}
                                    />
                                </div>
                            </div>
                        </div>

                        {/* CATEGORY BAR */}
                        <div className="col-md-6">
                            <h4 className="mb-2">Complaints Overview</h4>
                            <div className="card p-3 shadow-sm border-0" style={{ height: "380px" }}>

                                <Bar
                                    data={{
                                        labels: categories.slice(0, 5).map(i => i.name),

                                        datasets: [
                                            {
                                                label: "Complaints by Category",
                                                data: categories.slice(0, 5).map(i => i.value),
                                                backgroundColor: "#c82a2a38"
                                            }
                                        ]
                                    }}
                                />
                            </div>
                        </div>

                    </div>

                    {/* ROW 2 */}
                    <div className="row gy-4 mt-2">
                        <div className="row gy-4 mt-2">

                            {/* EMPLOYEE PERFORMANCE */}
                            <div className="col-md-6">
                                <h5 className="mb-2">Employee Workload</h5>
                                <div
                                    className="card p-3 shadow-sm border-0 d-flex justify-content-center align-items-center"
                                    style={{ height: "420px" }}
                                >
                                    <div style={{ width: "100%", height: "300px" }}>
                                        <Doughnut
                                            data={{
                                                labels: employeeLabels,
                                                datasets: [
                                                    {
                                                        label: "Assigned Issues",
                                                        data: employeeData,
                                                        backgroundColor: [
                                                            "#007bff",
                                                            "#28a745",
                                                            "#ffc107",
                                                            "#dc3545",
                                                            "#6f42c1",
                                                            "#20c997",
                                                            "#c92085"
                                                        ]
                                                    }
                                                ]
                                            }}
                                            options={{
                                                responsive: true,
                                                maintainAspectRatio: false,
                                                plugins: {
                                                    legend: {
                                                        position: "right"
                                                    }
                                                }
                                            }}
                                        />
                                    </div>
                                </div>
                            </div>

                            {/* DAILY ACTIVITY TREND */}
                            <div className="col-md-6">
                                <h5 className="mb-2">My Daily Activity</h5>
                                <div className="card p-3 shadow-sm border-0" style={{ height: "420px" }}>
                                    <Line
                                        data={{
                                            labels: dailyLabels,
                                            datasets: [
                                                {
                                                    label: "Issues Created (Last 7 Days)",
                                                    data: dailyCounts,
                                                    borderColor: "#198754",
                                                    backgroundColor: "rgba(25,135,84,0.15)",
                                                    fill: true,
                                                    tension: 0.4,
                                                    pointRadius: 4
                                                }
                                            ]
                                        }}
                                        options={{
                                            responsive: true,
                                            maintainAspectRatio: false,
                                            scales: {
                                                y: {
                                                    beginAtZero: true,
                                                    ticks: { precision: 0 }
                                                }
                                            }
                                        }}
                                    />

                                </div>
                            </div>

                        </div>

                    </div>
                </section>

                {/* REPORT MODAL */}
                {showReportsModal && (

                    <div className="reportModalOverlay">

                        <div className="reportModal">

                            {/* HEADER */}
                            <div className="reportHeader">

                                <div className="">
                                    <h2>Civora Analytics</h2>
                                    <p>Real-time complaint monitoring system</p>
                                </div>

                                <button
                                    className="closeModalBtn"
                                    onClick={() => setShowReportsModal(false)}
                                >
                                    <i className="bi bi-x-lg"></i>
                                </button>

                            </div>


                            {/* TOP STATS */}
                            <div className="reportStatsGrid">

                                <div className="reportStatCard">
                                    <h6>Resolution Rate</h6>

                                    <h3>
                                        {stats.total
                                            ? Math.round((stats.resolved / stats.total) * 100)
                                            : 0}%
                                    </h3>
                                </div>

                                <div className="reportStatCard">
                                    <h6>Pending Complaints</h6>
                                    <h3>{stats.pending}</h3>
                                </div>

                                <div className="reportStatCard">
                                    <h6>Departments Active</h6>
                                    <h3>{employeeLabels.length}</h3>
                                </div>

                            </div>


                            {/* MAIN CONTENT */}
                            <div className="reportContentGrid">

                                {/* CATEGORY SECTION */}
                                <div className="reportBox">

                                    <h4>Top Categories</h4>

                                    {categories.slice(0, 5).map((cat, index) => (

                                        <div
                                            className="categoryItem"
                                            key={index}
                                        >

                                            <div className="categoryLeft">

                                                <span className="dot"></span>

                                                <span>{cat.name}</span>

                                            </div>

                                            <span className="countBadge">
                                                {cat.value}
                                            </span>

                                        </div>

                                    ))}

                                </div>


                                {/* EMPLOYEE PERFORMANCE */}
                                <div className="reportBox">

                                    <h4>Employee Performance</h4>

                                    {employeeLabels.map((employee, index) => (

                                        <div
                                            className="employeeItem"
                                            key={index}
                                        >

                                            {/* LEFT */}
                                            <div className="employeeLeft">

                                                <div className="employeeAvatar">
                                                    {employee.charAt(0)}
                                                </div>

                                                <div>

                                                    <h5>{employee}</h5>

                                                    <small>
                                                        Complaint Resolution Team
                                                    </small>

                                                </div>

                                            </div>

                                            {/* RIGHT */}
                                            <div className="employeeRight">

                                                <span className="employeeCount">
                                                    {employeeData[index]} Issues
                                                </span>

                                            </div>

                                        </div>

                                    ))}

                                </div>

                            </div>


                            {/* FOOTER */}
                            <div className="reportFooter">

                                <div>
                                    Smart governance platform for efficient complaint management.
                                </div>

                                <button
                                    className="exportBtn"
                                    onClick={downloadReport}
                                >
                                    Export Report
                                </button>

                            </div>

                        </div>

                    </div>

                )}

            </div>
        </>

    );
}


/* ================= REUSABLE COMPONENTS ================= */

const StatCard = ({ icon, label, value }) => {
    return (
        <div className="col-md-3 col-6">
            <div className="stat-item shadow-sm p-3 rounded bg-light border">

                <div className="icon mb-2 text-primary">
                    <i className={`bi ${icon}`} style={{ fontSize: "24px" }}></i>
                </div>

                <span className="stat-number fs-4 fw-bold">
                    {value}
                </span>

                <span className="stat-label d-block text-muted">
                    {label}
                </span>

            </div>
        </div>
    );
};

const HighlightCard = ({ title, desc, badge, icon }) => {
    return (
        <div className="col-md-6">
            <div className="area-highlight shadow-sm p-3 rounded border bg-white">

                <div className="d-flex align-items-center mb-2">
                    <i className={`bi ${icon} me-2 text-primary`}></i>
                    <h5 className="mb-0">{title}</h5>
                </div>

                <p className="text-muted">{desc}</p>

                <span className="badge bg-secondary">{badge}</span>

            </div>
        </div>
    );
};

const InsightItem = ({ title, desc }) => {
    return (
        <div className="benefit-item d-flex mb-3">

            <div className="benefit-content">
                <h6 className="mb-0">{title}</h6>
                <small className="text-muted">{desc}</small>
            </div>

        </div>
    );
};